\documentclass[10pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage[version=4]{mhchem}
\usepackage{stmaryrd}
\allowdisplaybreaks


\begin{document}
<<include=FALSE,echo=FALSE>>=
options(width=60)
library(formatR)
@
Resolución \\
\\
1.1. \\
\\
1.2.\\
\\
1.3.\\
<<>>=
cat(sprintf("\nModelo 1. mean D = %8.2f. pD = %8.2f. DIC = %8.2f\n
Modelo 2. mean D = %8.2f. pD = %8.2f. DIC = %8.2f\n",
mean(D1), 0.5*var(D1), DIC1, mean(D2), 0.5*var(D2), DIC2))
@
El modelo 2 es más sencillo que el 1, y presenta mayor ajuste. Elijo por lo tanto el modelo 2.
Conclusión: El rendimiento en orientación  espacial es igual en hombres y mujeres. \\
\\
2.1. \\

\end{document}